FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

COPY toolchain.cmake /opt/toolchain.cmake

RUN apt-get update && apt-get install -y --no-install-recommends \
    clang \
    build-essential \
    cmake \
    gcc-mingw-w64-x86-64 \
    g++-mingw-w64-x86-64 \
    binutils-mingw-w64-x86-64 \
    && rm -rf /var/lib/apt/lists/*

ENV CROSS_TOOLCHAIN_PREFIX=x86_64-w64-mingw32-

ENV CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER="$CROSS_TOOLCHAIN_PREFIX"gcc \
    AR_x86_64_pc_windows_gnu="$CROSS_TOOLCHAIN_PREFIX"ar \
    CC_x86_64_pc_windows_gnu="$CROSS_TOOLCHAIN_PREFIX"gcc \
    CXX_x86_64_pc_windows_gnu="$CROSS_TOOLCHAIN_PREFIX"g++ \
    CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_gnu=/opt/toolchain.cmake \
    BINDGEN_EXTRA_CLANG_ARGS_x86_64_pc_windows_gnu="--target=x86_64-w64-windows-gnu" \
    CROSS_CMAKE_SYSTEM_NAME=Windows \
    CROSS_CMAKE_SYSTEM_PROCESSOR=x86_64 \
    CROSS_CMAKE_CRT=gnu \
    CROSS_CMAKE_OBJECT_FLAGS="-ffunction-sections -fdata-sections -fPIC"