FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

COPY toolchain.cmake /opt/toolchain.cmake

# Install dependencies required for rust build
RUN apt-get update && apt-get install -y --no-install-recommends \
    clang \
    build-essential \
    cmake \
    git \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Install dependencies for crosstool-ng: https://github.com/crosstool-ng/crosstool-ng/blob/185f3483e0e5028357b131fb97c4331551a70a1e/testing/docker/ubuntu22.04/Dockerfile#L13-L15
RUN apt-get update && apt-get install -y --no-install-recommends \
    autoconf \
    automake \
    bison \
    bzip2 \
    file \
    flex \
    gawk \
    gperf \
    help2man \
    libncurses-dev \
    libtool \
    libtool-bin \
    patch \
    python3 \
    rsync \
    texinfo \
    unzip \
    wget \
    xz-utils \
    && rm -rf /var/lib/apt/lists/*

# Crosstool ng doesn't allow root by default, but we don't care
ENV CT_EXPERIMENTAL=y \
    CT_ALLOW_BUILD_AS_ROOT=y \
    CT_ALLOW_BUILD_AS_ROOT_SURE=y \
    # Set toolchain prefix
    CT_PREFIX=/opt/x-tools \
    CT_TARGET=x86_64-unknown-linux-musl
# copy the crosstool config
COPY crosstool-ng/x86_64-unknown-linux-musl.config /crosstool.config

# Run the crosstool-ng toolchain build script and generate the toolchain
COPY crosstool-ng.sh /crosstool-ng.sh
RUN chmod +x /crosstool-ng.sh && \
    /crosstool-ng.sh

# Add it to path
ENV PATH="${CT_PREFIX}/$CT_TARGET/bin:${PATH}"

ENV CROSS_SYSROOT="$CT_PREFIX/$CT_TARGET/$CT_TARGET/sysroot"
ENV CROSS_TOOLCHAIN_PREFIX=${CT_TARGET}-
ENV CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER="$CROSS_TOOLCHAIN_PREFIX"gcc \
    AR_x86_64_unknown_linux_musl="$CROSS_TOOLCHAIN_PREFIX"ar \
    CC_x86_64_unknown_linux_musl="$CROSS_TOOLCHAIN_PREFIX"gcc \
    CXX_x86_64_unknown_linux_musl="$CROSS_TOOLCHAIN_PREFIX"g++ \
    CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_musl=/opt/toolchain.cmake \
    BINDGEN_EXTRA_CLANG_ARGS_x86_64_unknown_linux_musl="-idirafter/usr/include" \
    CROSS_CMAKE_SYSTEM_NAME=Linux \
    CROSS_CMAKE_SYSTEM_PROCESSOR=x86_64 \
    CROSS_CMAKE_CRT=musl \
    CROSS_CMAKE_OBJECT_FLAGS="-ffunction-sections -fdata-sections -fPIC -m64"

# link with glibc, because moonlight common c needs it
ENV LIBGCC_DIR=/opt/x-tools/x86_64-unknown-linux-musl/lib/gcc/x86_64-unknown-linux-musl/15.2.0
ENV CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_RUSTFLAGS="-C link-arg=-L${LIBGCC_DIR} -C link-arg=-lgcc"